import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { loadLocalEnv } from './lib/env-loader.mjs'

const root = process.cwd()
const args = new Set(process.argv.slice(2))
const printMode = args.has('--print')
const jsonMode = args.has('--json')
const writeLocalEnvTemplateMode =
  args.has('--write-local-env-template') ||
  args.has('--ad-provider-input-template') ||
  args.has('--monetization-input-template')
const templateOnlyMode = writeLocalEnvTemplateMode && args.has('--template-only')
const adProviderLocalEnvTemplateCommand = 'node scripts/monetization-planner.mjs --write-local-env-template'
const npmAdProviderLocalEnvTemplateCommand = 'npm run autonomous:ad-provider-input-template'
const setupAdProviderLocalEnvTemplateCommand = './ops/github/setup-production.sh --ad-provider-input-template'
const gatesPath = path.join(root, 'data', 'production-gates.json')
const readinessPath = path.join(root, 'data', 'production-readiness.json')
const promotionPath = path.join(root, 'data', 'promotion-decision.json')
const analyticsPath = path.join(root, 'data', 'analytics-rollup.json')
const growthPath = path.join(root, 'data', 'growth-plan.json')
const storePackagePath = path.join(root, 'data', 'store-package.json')
const environmentPath = path.join(root, 'data', 'production-environment.json')
const outputJsonPath = path.join(root, 'data', 'monetization-plan.json')
const outputTsPath = path.join(root, 'src', 'data', 'monetizationPlan.ts')
const reportPath = path.join(root, 'reports', 'monetization-plan-latest.md')
const appAdsPath = path.join(root, 'public', 'app-ads.txt')
const publicManifestPath = path.join(root, 'public', 'monetization.json')
const publicHtmlPath = path.join(root, 'public', 'monetization.html')

const readJson = async (filePath) => JSON.parse(await readFile(filePath, 'utf8'))
const readOptionalJson = async (filePath, fallback) =>
  readFile(filePath, 'utf8')
    .then((raw) => JSON.parse(raw))
    .catch(() => fallback)
const unique = (items) => [...new Set(items.filter(Boolean))]
const configured = (value) => typeof value === 'string' && value.trim().length > 0
const templateLineKey = (line) => {
  const match = String(line ?? '').trim().match(/^([A-Za-z_][A-Za-z0-9_]*)=$/)

  return match?.[1] ?? null
}
const assignedEnvKey = (line) => {
  const match = String(line ?? '').match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/)

  return match?.[1] ?? null
}
const safeLocalTemplatePath = (localEnvFile) => {
  const candidate = String(localEnvFile || '.env.production.local')

  if (path.isAbsolute(candidate) || candidate.split(/[\\/]+/).includes('..')) {
    throw new Error(`Refusing to write ad-provider input template outside the workspace: ${candidate}`)
  }

  return candidate
}
const writeLocalEnvTemplate = async (targetPack) => {
  const localEnvFile = safeLocalTemplatePath(targetPack?.localEnvFile)
  const localEnvPath = path.join(root, localEnvFile)
  const templateLines = unique(targetPack?.localEnvTemplateLines ?? [])
    .map((line) => String(line).trim())
    .filter((line) => templateLineKey(line))
  const existingRaw = await readFile(localEnvPath, 'utf8').catch((error) => {
    if (error?.code === 'ENOENT') {
      return ''
    }

    throw error
  })
  const existingKeys = new Set(existingRaw.split(/\r?\n/).map(assignedEnvKey).filter(Boolean))
  const linesToAdd = templateLines.filter((line) => !existingKeys.has(templateLineKey(line)))
  const addedKeys = linesToAdd.map(templateLineKey).filter(Boolean)

  if (linesToAdd.length === 0) {
    return {
      status: 'up-to-date',
      localEnvFile,
      addedKeys,
      preservedExistingValues: true,
      noSecretValuesWritten: true,
      noGithubMutation: true,
      gitIgnoredLocalEnvFile: true,
    }
  }

  const section = [
    '# Autonomous Game Lab ad-provider owner input',
    `# Generated by ${adProviderLocalEnvTemplateCommand}`,
    ...linesToAdd,
  ].join('\n')
  const separator = existingRaw.length ? (existingRaw.endsWith('\n') ? '\n' : '\n\n') : ''

  await mkdir(path.dirname(localEnvPath), { recursive: true })
  await writeFile(localEnvPath, `${existingRaw}${separator}${section}\n`)

  return {
    status: existingRaw.length ? 'appended-missing-template-lines' : 'created-template',
    localEnvFile,
    addedKeys,
    preservedExistingValues: true,
    noSecretValuesWritten: true,
    noGithubMutation: true,
    gitIgnoredLocalEnvFile: true,
  }
}
const escapeHtml = (value) =>
  String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')

const gates = await readJson(gatesPath)
const readiness = await readJson(readinessPath)
const promotion = await readJson(promotionPath)
const analytics = await readJson(analyticsPath)
const growth = await readJson(growthPath)
const storePackage = await readJson(storePackagePath)
const localEnv = await loadLocalEnv({ root })
const environment = await readOptionalJson(environmentPath, {
  monetization: { adNetworkProvider: 'google-admob', admobPublisherId: null },
})

const monetizationDecision = promotion.decisions?.find((decision) => decision.channel === 'monetization')
const metrics = readiness.monetization?.metrics ?? {}
const gatesPassed = readiness.monetization?.status === 'ready-for-low-risk-test'
const promotionAllowed = monetizationDecision?.status === 'promotable'
const adsenseClientId =
  process.env.VITE_ADSENSE_CLIENT_ID ??
  process.env.ADSENSE_CLIENT_ID ??
  environment.monetization?.adsenseClientId ??
  null
const adsenseRewardedSlotId =
  process.env.VITE_ADSENSE_REWARDED_SLOT_ID ??
  process.env.ADSENSE_REWARDED_SLOT_ID ??
  environment.monetization?.adsenseRewardedSlotId ??
  null
const admobPublisherId = process.env.ADMOB_PUBLISHER_ID ?? environment.monetization?.admobPublisherId ?? null
const webAdConfigured = Boolean(adsenseClientId && adsenseRewardedSlotId)
const appAdConfigured = Boolean(admobPublisherId)
const sellerId =
  process.env.AD_SELLER_ID ??
  admobPublisherId ??
  (adsenseClientId ? adsenseClientId.replace(/^ca-/, '') : null)
const adNetwork = {
  provider:
    process.env.AD_NETWORK_PROVIDER ??
    environment.monetization?.adNetworkProvider ??
    (webAdConfigured ? 'google-adsense' : 'google-admob'),
  publisherId: sellerId,
  sellerRelationship: process.env.AD_SELLER_RELATIONSHIP ?? 'DIRECT',
  certificationAuthorityId: process.env.AD_CERTIFICATION_AUTHORITY_ID ?? 'f08c47fec0942fa0',
  web: {
    provider: 'google-adsense',
    clientId: adsenseClientId,
    rewardedSlotId: adsenseRewardedSlotId,
    configured: webAdConfigured,
  },
  app: {
    provider: 'google-admob',
    publisherId: admobPublisherId,
    configured: appAdConfigured,
  },
}
const adNetworkConfigured = webAdConfigured || appAdConfigured
const canEnableRevenue = gatesPassed && promotionAllowed && adNetworkConfigured
const privacyPolicyHosted = storePackage.privacyPolicy?.productionUrlStatus === 'hosted'
const bestGrowthPage =
  growth.gamePages
    ?.slice()
    .sort((a, b) => (b.metrics?.qualityScore ?? 0) - (a.metrics?.qualityScore ?? 0))[0] ?? null

const placements = [
  {
    id: 'rewarded-hint-after-failed-daily',
    type: 'rewarded',
    status: canEnableRevenue ? 'ready' : 'disabled',
    firstChannel: 'web-pwa',
    trigger: 'after a completed failed run, never before the first game ends',
    reward: 'one optional strategy hint or cosmetic board accent',
    frequencyCap: 'max 1 offer per anonymous session',
    estimatedUserRisk: 'low',
    telemetry: [
      'rewarded_ad_available',
      'rewarded_ad_started',
      'rewarded_ad_completed',
      'revenue_cents',
    ],
  },
  {
    id: 'cosmetic-unlock-result-skin',
    type: 'cosmetic',
    status: gatesPassed && promotionAllowed ? 'planned' : 'disabled',
    firstChannel: 'web-pwa',
    trigger: 'result screen only',
    reward: 'alternate result-card look with no gameplay advantage',
    frequencyCap: 'offer after repeat play only',
    estimatedUserRisk: 'low',
    telemetry: ['cosmetic_offer_viewed', 'cosmetic_offer_clicked', 'revenue_cents'],
  },
]

const blockers = [
  ...(readiness.monetization?.checks ?? [])
    .filter((check) => check.status !== 'pass')
    .map((check) => check.detail),
  ...(promotionAllowed ? [] : monetizationDecision?.blockers ?? ['Monetization promotion is not allowed.']),
  ...(adNetworkConfigured
    ? []
    : ['Web/PWA or native ad provider is not configured for gated revenue tests.']),
].filter((blocker, index, items) => items.indexOf(blocker) === index)

const status = canEnableRevenue
  ? 'ready-for-rewarded-test'
  : gatesPassed && promotionAllowed
    ? 'ready-needs-ad-network'
    : 'blocked-by-product-gates'

const preflightChecks = [
  {
    id: 'product-gates',
    status: gatesPassed ? 'pass' : 'blocked',
    detail: `Readiness is ${readiness.monetization?.status ?? 'missing'}; first-game completion, replay, and D1 retention must pass before revenue tests.`,
  },
  {
    id: 'promotion-gate',
    status: promotionAllowed ? 'pass' : 'blocked',
    detail: `Promotion decision is ${monetizationDecision?.status ?? 'missing'}; release health must allow monetization.`,
  },
  {
    id: 'ad-provider',
    status: adNetworkConfigured ? 'pass' : 'missing-config',
    detail: webAdConfigured
      ? 'Web/PWA AdSense client and rewarded/display slot are configured.'
      : appAdConfigured
        ? 'Native AdMob publisher id is configured.'
        : 'Set VITE_ADSENSE_CLIENT_ID + VITE_ADSENSE_REWARDED_SLOT_ID or ADMOB_PUBLISHER_ID before running revenue tests.',
  },
  {
    id: 'privacy-policy',
    status: privacyPolicyHosted ? 'pass' : 'blocked',
    detail: `Privacy policy URL is ${storePackage.privacyPolicy?.productionUrlStatus ?? 'missing'}.`,
  },
  {
    id: 'runtime-guardrails',
    status: 'pass',
    detail: 'Rewarded placement waits for a completed failed run, is capped to one offer per session, and never paywalls core rules.',
  },
  {
    id: 'telemetry-contract',
    status: 'pass',
    detail: 'Revenue telemetry is limited to rewarded/cosmetic lifecycle events and revenue_cents.',
  },
  {
    id: 'spend-guard',
    status: 'pass',
    detail: 'Revenue preflight does not allow paid acquisition, app-store spend, or store submission.',
  },
]
const preflightBlockingChecks = preflightChecks.filter((check) => check.status !== 'pass')
const preflightCheckSummary = preflightChecks.map(({ id, status }) => ({ id, status }))
const revenueTestPreflight = {
  status: canEnableRevenue
    ? 'ready-to-arm'
    : preflightBlockingChecks.some((check) => check.id === 'ad-provider')
      ? 'waiting-on-provider-or-product-gates'
      : 'waiting-on-product-gates',
  canArmRevenueTest: canEnableRevenue,
  firstRunnablePlacementId: placements[0].id,
  checks: preflightCheckSummary,
  blockingCheckIds: preflightBlockingChecks.map((check) => check.id),
  requiredEnvironment: {
    web: [
      { name: 'VITE_ADSENSE_CLIENT_ID', configured: Boolean(adsenseClientId) },
      { name: 'VITE_ADSENSE_REWARDED_SLOT_ID', configured: Boolean(adsenseRewardedSlotId) },
    ],
    native: [{ name: 'ADMOB_PUBLISHER_ID', configured: Boolean(admobPublisherId) }],
  },
  validationCommands: [
    'npm run autonomous:monetization',
    'npm run autonomous:unit-economics',
    'npm run autonomous:store-compliance',
    'npm run autonomous:readiness',
  ],
  controls: {
    noRevenueEnablementUntilAllChecksPass: true,
    noPaidSpend: true,
    noStoreSubmission: true,
    noSecretValues: true,
  },
}
const adProviderInputNames = ['VITE_ADSENSE_CLIENT_ID', 'VITE_ADSENSE_REWARDED_SLOT_ID', 'ADMOB_PUBLISHER_ID']
const adProviderConfiguredInputNames = adProviderInputNames.filter((name) => configured(process.env[name]))
const adProviderMissingInputNames = adProviderInputNames.filter((name) => !configured(process.env[name]))
const adProviderOwnerInputPack = {
  id: 'zero-secret-ad-provider-input-pack',
  title: 'Zero-secret ad provider input pack',
  unlockId: 'ad-provider-config',
  status: adNetworkConfigured ? 'ad-provider-configured' : 'ad-provider-input-ready',
  readyForProviderSetup: adNetworkConfigured,
  revenueStillBlockedUntilProductGatesPass: !canEnableRevenue,
  productGatesPassed: gatesPassed,
  promotionAllowed,
  localEnvFile: '.env.production.local',
  localEnvLoadedFiles: localEnv.loadedFiles?.map((file) => file.path) ?? [],
  configuredInputNames: adProviderConfiguredInputNames,
  missingInputNames: adProviderMissingInputNames,
  missingInputCount: adProviderMissingInputNames.length,
  secretInputCount: 0,
  providerPaths: [
    {
      id: 'web-adsense',
      title: 'Web/PWA AdSense rewarded test',
      status: webAdConfigured ? 'configured' : 'waiting-on-public-provider-ids',
      requiredInputNames: ['VITE_ADSENSE_CLIENT_ID', 'VITE_ADSENSE_REWARDED_SLOT_ID'],
      configured: webAdConfigured,
      firstPlacementId: placements[0].id,
      revenueGateStillApplies: true,
    },
    {
      id: 'native-admob',
      title: 'Native AdMob seller line',
      status: appAdConfigured ? 'configured' : 'waiting-on-public-publisher-id',
      requiredInputNames: ['ADMOB_PUBLISHER_ID'],
      configured: appAdConfigured,
      appAdsTxtPath: '/app-ads.txt',
      revenueGateStillApplies: true,
    },
  ],
  localEnvTemplateLines: adProviderMissingInputNames.map((name) => `${name}=`),
  shellExportTemplateLines: adProviderMissingInputNames.map((name) => `export ${name}=`),
  commands: {
    npmWriteLocalEnvTemplate: npmAdProviderLocalEnvTemplateCommand,
    writeLocalEnvTemplate: adProviderLocalEnvTemplateCommand,
    setupWriteLocalEnvTemplate: setupAdProviderLocalEnvTemplateCommand,
    syncConfiguredValues: './ops/github/setup-production.sh',
    refreshMonetization: 'npm run autonomous:monetization',
    refreshUnitEconomics: 'npm run autonomous:unit-economics',
    refreshReadiness: 'npm run autonomous:readiness',
  },
  browserLocalActionPack: {
    id: 'browser-local-ad-provider-action-pack',
    status: 'ready',
    receiptStorageKey: 'agl.adProviderActionReceipt',
    filledDownloadFileName: 'agl-ad-provider.env',
    fields: [
      {
        envName: 'VITE_ADSENSE_CLIENT_ID',
        title: 'AdSense client id',
        inputId: 'ad-provider-vite-adsense-client-id',
        validationKind: 'adsense-client-id',
        inputType: 'text',
        placeholder: 'ca-pub-0000000000000000',
        requiredForPath: 'web-adsense',
        publicValue: true,
        maxLength: 64,
      },
      {
        envName: 'VITE_ADSENSE_REWARDED_SLOT_ID',
        title: 'AdSense rewarded slot id',
        inputId: 'ad-provider-vite-adsense-rewarded-slot-id',
        validationKind: 'numeric-ad-slot',
        inputType: 'text',
        placeholder: '1234567890',
        requiredForPath: 'web-adsense',
        publicValue: true,
        maxLength: 32,
      },
      {
        envName: 'ADMOB_PUBLISHER_ID',
        title: 'AdMob publisher id',
        inputId: 'ad-provider-admob-publisher-id',
        validationKind: 'admob-publisher-id',
        inputType: 'text',
        placeholder: 'pub-0000000000000000',
        requiredForPath: 'native-admob',
        publicValue: true,
        maxLength: 64,
      },
    ],
    commands: {
      githubVariableSetAdsenseClient: 'gh variable set VITE_ADSENSE_CLIENT_ID --body "$VITE_ADSENSE_CLIENT_ID"',
      githubVariableSetAdsenseRewardedSlot:
        'gh variable set VITE_ADSENSE_REWARDED_SLOT_ID --body "$VITE_ADSENSE_REWARDED_SLOT_ID"',
      githubVariableSetAdmobPublisher: 'gh variable set ADMOB_PUBLISHER_ID --body "$ADMOB_PUBLISHER_ID"',
      validate: 'npm run autonomous:monetization',
      readiness: 'npm run autonomous:readiness',
    },
    controls: {
      browserLocalOnly: true,
      publicValuesOnly: true,
      noGeneratedValueSerialization: true,
      noSecretValues: true,
      noGithubMutation: true,
      noWorkflowDispatch: true,
      noRevenueEnablement: true,
      noPaidSpend: true,
      noStoreSubmission: true,
      productGatesStillRequired: true,
    },
  },
  controls: {
    zeroPaidSpend: true,
    publicValuesOnly: true,
    noSecretValuesStored: true,
    noSecretValuesSerialized: true,
    noMutation: true,
    noWorkflowDispatch: true,
    noRevenueEnablement: true,
    noPaidSpend: true,
    noStoreSubmission: true,
    productGatesStillRequired: true,
    gitIgnoredLocalEnvFile: true,
    localTemplateWriteNoSecretValues: true,
    localTemplateWritePreservesExistingValues: true,
    localTemplateWriteNoGithubMutation: true,
  },
}

const payload = {
  generatedAt: new Date().toISOString(),
  status,
  revenueEnabled: canEnableRevenue,
  costPosture: 'no-new-spend-until-gates-pass',
  analyticsSource: analytics.sourceStatus?.activeSource,
  retentionSource: analytics.retention?.source ?? readiness.monetization?.metrics?.retentionSource,
  metrics: {
    firstGameCompletion: metrics.firstGameCompletion ?? analytics.totals?.metrics?.firstGameCompletion,
    replayRate: metrics.replayRate ?? analytics.totals?.metrics?.replayRate,
    d1Retention: metrics.d1Retention ?? analytics.totals?.metrics?.d1Retention,
    revenueCents: analytics.totals?.metrics?.revenueCents ?? 0,
  },
  gates: {
    requiredStatus: 'ready-for-low-risk-test',
    readinessStatus: readiness.monetization?.status,
    promotionStatus: monetizationDecision?.status ?? 'missing',
    allowedEarlyTests: gates.monetization.allowedEarlyTests,
    blockedBeforeRetention: gates.monetization.blockedBeforeRetention,
  },
  adNetwork,
  revenueTestPreflight,
  adProviderOwnerInputPack,
  placements,
  blockers,
  launchCandidate: bestGrowthPage
    ? {
        gameId: bestGrowthPage.gameId,
        title: bestGrowthPage.title,
        pagePath: bestGrowthPage.pagePath,
        qualityScore: bestGrowthPage.metrics?.qualityScore ?? null,
      }
    : null,
  compliance: {
    privacyPolicyPath: storePackage.privacyPolicy?.path,
    privacyPolicyStatus: storePackage.privacyPolicy?.productionUrlStatus,
    appAdsTxtPath: '/app-ads.txt',
    adDisclosureRequiredWhenEnabled: true,
    purchasesDisabledUntilExplicitGate: true,
  },
  publicRoutes: {
    monetization: '/monetization.html',
    monetizationJson: '/monetization.json',
    appAdsTxt: '/app-ads.txt',
    measurementStatus: '/measurement-status.html',
    gateSample: '/gate-sample.html',
    privacyPolicy: storePackage.privacyPolicy?.path ?? '/privacy.html',
  },
  safety: {
    neverEnableBeforeRetention: gates.monetization.blockedBeforeRetention,
    firstAllowedPlacement: placements[0].id,
    noInterstitialsInFirstSession: true,
    noPaywalledCoreRules: true,
  },
  runtime: {
    status: canEnableRevenue ? 'armed' : 'guarded-disabled',
    surface: 'result-screen',
    firstPlacementId: placements[0].id,
    requiresCompletedRun: true,
    requiresFailedRun: true,
    maxOffersPerSession: 1,
    disabledReason: blockers[0] ?? null,
    blockedEventsWhenDisabled: ['rewarded_ad_started', 'rewarded_ad_completed', 'revenue_cents'],
    webAdapter: webAdConfigured ? 'adsense-configured' : 'adsense-not-configured',
    appAdapter: appAdConfigured ? 'admob-configured' : 'admob-not-configured',
  },
}

const appAdsText = adNetworkConfigured
  ? `google.com, ${adNetwork.publisherId}, ${adNetwork.sellerRelationship}, ${adNetwork.certificationAuthorityId}\n`
  : [
      '# Autonomous Game Lab app-ads.txt',
      '# Revenue features are disabled until product, privacy, and platform gates pass.',
      '# Set ADMOB_PUBLISHER_ID to generate a valid seller line automatically.',
      '',
    ].join('\n')

const publicManifest = {
  generatedAt: payload.generatedAt,
  status: payload.status,
  revenueEnabled: payload.revenueEnabled,
  revenueTestPreflight: {
    status: payload.revenueTestPreflight.status,
    canArmRevenueTest: payload.revenueTestPreflight.canArmRevenueTest,
    blockingCheckIds: payload.revenueTestPreflight.blockingCheckIds,
    checks: payload.revenueTestPreflight.checks.map((check) => ({
      id: check.id,
      status: check.status,
    })),
    controls: payload.revenueTestPreflight.controls,
  },
  adProviderOwnerInputPack: {
    id: payload.adProviderOwnerInputPack.id,
    unlockId: payload.adProviderOwnerInputPack.unlockId,
    status: payload.adProviderOwnerInputPack.status,
    missingInputCount: payload.adProviderOwnerInputPack.missingInputCount,
    secretInputCount: payload.adProviderOwnerInputPack.secretInputCount,
    providerPaths: payload.adProviderOwnerInputPack.providerPaths.map((providerPath) => ({
      id: providerPath.id,
      status: providerPath.status,
      configured: providerPath.configured,
      revenueGateStillApplies: providerPath.revenueGateStillApplies,
    })),
    browserLocalActionPack: {
      id: payload.adProviderOwnerInputPack.browserLocalActionPack.id,
      receiptStorageKey: payload.adProviderOwnerInputPack.browserLocalActionPack.receiptStorageKey,
      filledDownloadFileName: payload.adProviderOwnerInputPack.browserLocalActionPack.filledDownloadFileName,
      controls: payload.adProviderOwnerInputPack.browserLocalActionPack.controls,
    },
    controls: payload.adProviderOwnerInputPack.controls,
  },
  publicRoutes: payload.publicRoutes,
  runtime: payload.runtime,
  placements: payload.placements.map((placement) => ({
    id: placement.id,
    status: placement.status,
    type: placement.type,
  })),
}

const report = [
  '# Monetization Plan',
  '',
  `Generated: ${payload.generatedAt}`,
  `Status: ${payload.status}`,
  `Revenue enabled: ${payload.revenueEnabled}`,
  `Analytics source: ${payload.analyticsSource}`,
  `Runtime: ${payload.runtime.status}`,
  `Revenue test preflight: ${payload.revenueTestPreflight.status}`,
  `Public preflight: ${payload.publicRoutes.monetization}`,
  '',
  '## Metrics',
  '',
  `- First-game completion: ${Math.round((payload.metrics.firstGameCompletion ?? 0) * 100)}%`,
  `- Replay rate: ${Math.round((payload.metrics.replayRate ?? 0) * 100)}%`,
  `- D1 retention: ${Math.round((payload.metrics.d1Retention ?? 0) * 100)}%`,
  `- Revenue: $${((payload.metrics.revenueCents ?? 0) / 100).toFixed(2)}`,
  '',
  '## Placements',
  '',
  ...payload.placements.map(
    (placement) =>
      `- ${placement.status}: ${placement.id} (${placement.type}) - ${placement.trigger}; ${placement.frequencyCap}.`,
  ),
  '',
  '## Blockers',
  '',
  ...(payload.blockers.length ? payload.blockers.map((blocker) => `- ${blocker}`) : ['- none']),
  '',
  '## Revenue Test Preflight',
  '',
  ...preflightChecks.map((check) => `- ${check.status}: ${check.id} - ${check.detail}`),
  '',
  '## Ad Provider Input Pack',
  '',
  `- status: ${adProviderOwnerInputPack.status}`,
  `- unlock: ${adProviderOwnerInputPack.unlockId}`,
  `- local env file: ${adProviderOwnerInputPack.localEnvFile}`,
  `- npm template: ${adProviderOwnerInputPack.commands.npmWriteLocalEnvTemplate}`,
  `- write local env template: ${adProviderOwnerInputPack.commands.writeLocalEnvTemplate}`,
  `- setup write local env template: ${adProviderOwnerInputPack.commands.setupWriteLocalEnvTemplate}`,
  `- missing inputs: ${adProviderOwnerInputPack.missingInputNames.join(', ') || 'none'}`,
  `- secret inputs: ${adProviderOwnerInputPack.secretInputCount}`,
  `- browser-local action pack: ${adProviderOwnerInputPack.browserLocalActionPack.id}`,
  `- browser-local receipt key: ${adProviderOwnerInputPack.browserLocalActionPack.receiptStorageKey}`,
  `- browser-local download file: ${adProviderOwnerInputPack.browserLocalActionPack.filledDownloadFileName}`,
  `- product gates still required: ${adProviderOwnerInputPack.controls.productGatesStillRequired}`,
  `- no revenue enablement: ${adProviderOwnerInputPack.controls.noRevenueEnablement}`,
  ...(adProviderOwnerInputPack.localEnvTemplateLines.length
    ? ['- local env template:', ...adProviderOwnerInputPack.localEnvTemplateLines.map((line) => `  - ${line}`)]
    : ['- local env template: none']),
  '',
  '## Validation',
  '',
  ...payload.revenueTestPreflight.validationCommands.map((command) => `- ${command}`),
  '',
  '## Safety',
  '',
  ...payload.safety.neverEnableBeforeRetention.map((item) => `- blocked before retention: ${item}`),
  '- no interstitials in the first session',
  '- no paywalled core rules',
  '',
  '## Runtime',
  '',
  `- Surface: ${payload.runtime.surface}`,
  `- First placement: ${payload.runtime.firstPlacementId}`,
  `- Web adapter: ${payload.runtime.webAdapter}`,
  `- App adapter: ${payload.runtime.appAdapter}`,
  `- Disabled reason: ${payload.runtime.disabledReason ?? 'none'}`,
  '',
]

const publicHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Autonomous Game Lab Monetization Preflight</title>
    <style>
      :root {
        color: #16211f;
        background: #f6f8f7;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      }

      * {
        box-sizing: border-box;
      }

      body {
        margin: 0;
      }

      header,
      main {
        width: min(1120px, calc(100% - 32px));
        margin: 0 auto;
      }

      header {
        padding: 42px 0 22px;
      }

      h1,
      h2,
      p {
        margin: 0;
      }

      h1 {
        max-width: 760px;
        font-size: clamp(2rem, 5vw, 4.4rem);
        line-height: 0.98;
        letter-spacing: 0;
      }

      h2 {
        font-size: 1.2rem;
        letter-spacing: 0;
      }

      p {
        color: #4d5c58;
        line-height: 1.55;
      }

      header p:not(.eyebrow) {
        max-width: 720px;
        margin-top: 14px;
        font-size: 1.05rem;
      }

      .eyebrow {
        margin-bottom: 10px;
        color: #0f766e;
        font-size: 0.76rem;
        font-weight: 800;
        letter-spacing: 0;
        text-transform: uppercase;
      }

      .summary,
      .checks,
      .placements,
      .provider-grid {
        display: grid;
        gap: 12px;
      }

      .summary {
        grid-template-columns: repeat(4, minmax(0, 1fr));
        padding: 18px 0 22px;
      }

      .checks,
      .placements,
      .provider-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }

      .placements {
        margin-top: 14px;
      }

      .metric,
      .check,
      .placement,
      .handoff,
      label {
        border: 1px solid #c9d6d2;
        border-radius: 8px;
        background: #ffffff;
        padding: 16px;
      }

      .metric span,
      .check span,
      .placement span,
      label span {
        display: block;
        color: #68736f;
        font-size: 0.76rem;
        font-weight: 800;
        text-transform: uppercase;
      }

      .metric strong,
      .check strong,
      .placement strong {
        display: block;
        margin-top: 5px;
        overflow-wrap: anywhere;
        font-size: 1.05rem;
      }

      .check p,
      .placement p {
        margin-top: 10px;
      }

      section {
        margin-bottom: 24px;
      }

      section > h2 {
        margin-bottom: 12px;
      }

      .handoff {
        margin: 24px 0 42px;
      }

      .actions {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
        margin-top: 14px;
      }

      input {
        width: 100%;
        min-height: 42px;
        margin-top: 8px;
        border: 1px solid #b9c8c4;
        border-radius: 7px;
        padding: 0 12px;
        color: #16211f;
        font: inherit;
      }

      button {
        min-height: 42px;
        border: 0;
        border-radius: 7px;
        background: #0f766e;
        color: #ffffff;
        cursor: pointer;
        font: inherit;
        font-weight: 800;
        padding: 0 14px;
      }

      button:nth-child(3) {
        background: #31423d;
      }

      button:nth-child(4) {
        background: #bd4d38;
      }

      button:disabled {
        cursor: not-allowed;
        opacity: 0.5;
      }

      .status-line {
        margin-top: 12px;
      }

      a {
        color: #0f5f58;
        font-weight: 800;
      }

      .actions a {
        display: inline-flex;
        min-height: 42px;
        align-items: center;
        justify-content: center;
        padding: 0 14px;
        border-radius: 7px;
        background: #0f766e;
        color: #ffffff;
        text-decoration: none;
      }

      .actions a:nth-child(2) {
        background: #31423d;
      }

      .actions a:nth-child(3) {
        background: #bd4d38;
      }

      @media (max-width: 820px) {
        .summary,
        .checks,
        .placements,
        .provider-grid {
          grid-template-columns: 1fr;
        }
      }
    </style>
  </head>
  <body>
    <header>
      <p class="eyebrow">Zero-spend revenue gate</p>
      <h1>Autonomous Game Lab Monetization Preflight</h1>
      <p>Rewarded and cosmetic revenue tests stay disabled until product gates, promotion safety, provider setup, privacy, and spend controls all pass.</p>
    </header>
    <main>
      <section class="summary" aria-label="Monetization summary">
        <div class="metric"><span>Status</span><strong>${escapeHtml(payload.status)}</strong></div>
        <div class="metric"><span>Revenue enabled</span><strong>${payload.revenueEnabled ? 'yes' : 'no'}</strong></div>
        <div class="metric"><span>Preflight</span><strong>${escapeHtml(payload.revenueTestPreflight.status)}</strong></div>
        <div class="metric"><span>Runtime</span><strong>${escapeHtml(payload.runtime.status)}</strong></div>
      </section>
      <section aria-label="Revenue test checks">
        <h2>Revenue Test Checks</h2>
        <div class="checks">
          ${preflightChecks
            .map(
              (check) => `<article class="check">
                <span>${escapeHtml(check.id)}</span>
                <strong>${escapeHtml(check.status)}</strong>
                <p>${escapeHtml(check.detail)}</p>
              </article>`,
            )
            .join('')}
        </div>
      </section>
      <section aria-label="Revenue placements">
        <h2>Placements</h2>
        <div class="placements">
          ${payload.placements
            .map(
              (placement) => `<article class="placement">
                <span>${escapeHtml(placement.type)}</span>
                <strong>${escapeHtml(placement.id)}: ${escapeHtml(placement.status)}</strong>
                <p>${escapeHtml(placement.trigger)} ${escapeHtml(placement.frequencyCap)}</p>
              </article>`,
            )
            .join('')}
        </div>
      </section>
      <section class="handoff" aria-label="Ad provider input pack">
        <h2>Ad Provider Input Pack</h2>
        <p>Prepare public AdSense or AdMob identifiers locally. The runtime stays guarded until product, promotion, privacy, and spend gates pass.</p>
        <p>Unlock: <strong>${escapeHtml(adProviderOwnerInputPack.unlockId)}</strong>. Status: <strong>${escapeHtml(adProviderOwnerInputPack.status)}</strong>.</p>
        <div class="provider-grid">
          ${adProviderOwnerInputPack.browserLocalActionPack.fields
            .map(
              (field) => `<label for="${escapeHtml(field.inputId)}">
                <span>${escapeHtml(field.title)}</span>
                <input
                  id="${escapeHtml(field.inputId)}"
                  type="${escapeHtml(field.inputType)}"
                  maxlength="${field.maxLength}"
                  placeholder="${escapeHtml(field.placeholder)}"
                  autocomplete="off"
                  spellcheck="false"
                />
              </label>`,
            )
            .join('')}
        </div>
        <div class="actions">
          <button id="validate-ad-provider-input" type="button">Check provider IDs</button>
          <button id="download-filled-ad-provider-template" type="button" disabled>Download provider env</button>
          <button id="copy-filled-ad-provider-shell" type="button" disabled>Copy shell exports</button>
          <button id="copy-ad-provider-variable-command" type="button" disabled>Copy GitHub variable commands</button>
        </div>
        <p class="status-line" id="ad-provider-validation-status" aria-live="polite">Waiting for provider IDs. Typed values stay in this browser session unless you choose a local download or copy action.</p>
      </section>
      <section class="handoff" aria-label="Monetization handoff">
        <h2>Handoff</h2>
        <p>Current blocker: ${escapeHtml(payload.runtime.disabledReason ?? 'none')}. Revenue, paid acquisition, and store submission remain blocked while this preflight is not ready.</p>
        <div class="actions">
          <a href="./measurement-status.html">Open measurement status</a>
          <a href="./gate-sample.html">Open gate sample</a>
          <a href="./monetization.json">Open monetization JSON</a>
          <a href="./app-ads.txt">Open app-ads.txt</a>
        </div>
      </section>
    </main>
    <script>
      (() => {
        const adProviderOwnerInputPack = ${JSON.stringify(adProviderOwnerInputPack)}
        const status = document.getElementById('ad-provider-validation-status')
        const validateButton = document.getElementById('validate-ad-provider-input')
        const downloadButton = document.getElementById('download-filled-ad-provider-template')
        const copyShellButton = document.getElementById('copy-filled-ad-provider-shell')
        const copyCommandButton = document.getElementById('copy-ad-provider-variable-command')
        const fieldInputs = new Map(
          adProviderOwnerInputPack.browserLocalActionPack.fields.map((field) => [
            field.envName,
            document.getElementById(field.inputId),
          ]),
        )

        const setStatus = (message) => {
          if (status) {
            status.textContent = message
          }
        }
        const setActionButtons = (enabled) => {
          for (const button of [downloadButton, copyShellButton, copyCommandButton]) {
            if (button) {
              button.disabled = !enabled
            }
          }
        }
        const readValues = () =>
          Object.fromEntries(
            [...fieldInputs.entries()]
              .map(([name, input]) => [name, input?.value?.trim() ?? ''])
              .filter(([, value]) => value),
          )
        const validateValues = () => {
          const values = readValues()
          const client = values.VITE_ADSENSE_CLIENT_ID ?? ''
          const slot = values.VITE_ADSENSE_REWARDED_SLOT_ID ?? ''
          const admob = values.ADMOB_PUBLISHER_ID ?? ''
          const errors = []
          const clientValid = !client || /^ca-pub-\\d{8,24}$/.test(client)
          const slotValid = !slot || /^\\d{4,32}$/.test(slot)
          const admobValid = !admob || /^pub-\\d{8,24}$/.test(admob)
          const webPartial = Boolean(client) !== Boolean(slot)
          const webReady = Boolean(client && slot && clientValid && slotValid)
          const nativeReady = Boolean(admob && admobValid)

          if (webPartial) {
            errors.push('AdSense needs both client id and rewarded slot id.')
          }
          if (!clientValid) {
            errors.push('AdSense client id should look like ca-pub-0000000000000000.')
          }
          if (!slotValid) {
            errors.push('Rewarded slot id should be numeric.')
          }
          if (!admobValid) {
            errors.push('AdMob publisher id should look like pub-0000000000000000.')
          }
          if (!webReady && !nativeReady) {
            errors.push('Enter a complete Web AdSense pair or a native AdMob publisher id.')
          }

          return {
            ok: errors.length === 0,
            errors,
            providerPath: webReady ? 'web-adsense' : nativeReady ? 'native-admob' : null,
            values,
          }
        }
        const envText = (values) => Object.entries(values).map(([name, value]) => name + '=' + value).join('\\n') + '\\n'
        const shellText = (values) =>
          Object.entries(values).map(([name, value]) => 'export ' + name + '=' + value).join('\\n') + '\\n'
        const commandText = (values) =>
          Object.keys(values).map((name) => 'gh variable set ' + name + ' --body "$' + name + '"').join('\\n') + '\\n'
        const downloadText = (text, fileName) => {
          const blob = new Blob([text], { type: 'text/plain' })
          const url = URL.createObjectURL(blob)
          const link = document.createElement('a')
          link.href = url
          link.download = fileName
          document.body.append(link)
          link.click()
          link.remove()
          URL.revokeObjectURL(url)
        }
        const writeReceipt = (action, validation, extra = {}) => {
          const receipt = {
            action,
            actionPackId: adProviderOwnerInputPack.browserLocalActionPack.id,
            unlockId: adProviderOwnerInputPack.unlockId,
            providerPath: validation.providerPath,
            inputNames: Object.keys(validation.values),
            validatedInputNames: Object.keys(validation.values),
            validationStatus: validation.ok ? 'passed' : 'failed',
            productGatesStillRequired: adProviderOwnerInputPack.controls.productGatesStillRequired === true,
            noRevenueEnablement: adProviderOwnerInputPack.controls.noRevenueEnablement === true,
            noPaidSpend: adProviderOwnerInputPack.controls.noPaidSpend === true,
            noGithubMutation: adProviderOwnerInputPack.browserLocalActionPack.controls.noGithubMutation === true,
            noValuesStored: adProviderOwnerInputPack.browserLocalActionPack.controls.noGeneratedValueSerialization === true,
            createdAt: new Date().toISOString(),
            ...extra,
          }
          window.localStorage.setItem(
            adProviderOwnerInputPack.browserLocalActionPack.receiptStorageKey,
            JSON.stringify(receipt),
          )
        }
        const validateAndReport = () => {
          const result = validateValues()
          setActionButtons(result.ok)

          if (!result.ok) {
            setStatus(result.errors.join(' '))
            return result
          }

          writeReceipt('validate-ad-provider-input', result)
          setStatus(
            result.providerPath === 'web-adsense'
              ? 'Web AdSense provider IDs look ready. Revenue gates still apply.'
              : 'Native AdMob publisher ID looks ready. Revenue gates still apply.',
          )
          return result
        }

        validateButton?.addEventListener('click', validateAndReport)
        for (const input of fieldInputs.values()) {
          input?.addEventListener('input', () => {
            setActionButtons(false)
            setStatus('Provider IDs changed. Check them before downloading or copying.')
          })
        }
        downloadButton?.addEventListener('click', () => {
          const result = validateAndReport()
          if (!result.ok) {
            return
          }
          downloadText(envText(result.values), adProviderOwnerInputPack.browserLocalActionPack.filledDownloadFileName)
          writeReceipt('download-ad-provider-env', result, {
            fileName: adProviderOwnerInputPack.browserLocalActionPack.filledDownloadFileName,
          })
          setStatus('Provider env downloaded. Revenue gates still apply.')
        })
        copyShellButton?.addEventListener('click', async () => {
          const result = validateAndReport()
          if (!result.ok) {
            return
          }
          if (!navigator.clipboard?.writeText) {
            setStatus('Clipboard is unavailable in this browser session.')
            return
          }
          try {
            await navigator.clipboard.writeText(shellText(result.values))
            writeReceipt('copy-ad-provider-shell-export', result)
            setStatus('Provider shell exports copied. Revenue gates still apply.')
          } catch {
            setStatus('Clipboard is unavailable in this browser session.')
          }
        })
        copyCommandButton?.addEventListener('click', async () => {
          const result = validateAndReport()
          if (!result.ok) {
            return
          }
          if (!navigator.clipboard?.writeText) {
            setStatus('Clipboard is unavailable in this browser session.')
            return
          }
          try {
            await navigator.clipboard.writeText(commandText(result.values))
            writeReceipt('copy-ad-provider-variable-command', result, { commandRequiresOwnerRun: true })
            setStatus('GitHub variable commands copied. Revenue gates still apply.')
          } catch {
            setStatus('Clipboard is unavailable in this browser session.')
          }
        })
      })()
    </script>
  </body>
</html>
`

const localTemplateWriteResult = writeLocalEnvTemplateMode ? await writeLocalEnvTemplate(adProviderOwnerInputPack) : null

if (!templateOnlyMode) {
  await mkdir(path.dirname(outputJsonPath), { recursive: true })
  await mkdir(path.dirname(outputTsPath), { recursive: true })
  await mkdir(path.dirname(reportPath), { recursive: true })
  await mkdir(path.dirname(appAdsPath), { recursive: true })
  await writeFile(outputJsonPath, JSON.stringify(payload, null, 2) + '\n')
  await writeFile(
    outputTsPath,
    `export const monetizationPlan = ${JSON.stringify(payload, null, 2)} as const\n\nexport type MonetizationPlan = typeof monetizationPlan\n`,
  )
  await writeFile(publicManifestPath, JSON.stringify(publicManifest, null, 2) + '\n')
  await writeFile(publicHtmlPath, publicHtml)
  await writeFile(appAdsPath, appAdsText)
  await writeFile(reportPath, report.join('\n'))
}

if (jsonMode) {
  process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`)
} else if (printMode) {
  const output = [
    'Monetization Plan',
    `Status: ${payload.status}`,
    `Revenue enabled: ${payload.revenueEnabled}`,
    `Revenue test preflight: ${payload.revenueTestPreflight.status}`,
    `Ad provider input pack: ${adProviderOwnerInputPack.status}`,
    `Local env file: ${adProviderOwnerInputPack.localEnvFile}`,
    `Missing inputs: ${adProviderOwnerInputPack.missingInputNames.join(', ') || 'none'}`,
    '',
    'Commands:',
    `  - NPM template: ${adProviderOwnerInputPack.commands.npmWriteLocalEnvTemplate}`,
    `  - Write local env template: ${adProviderOwnerInputPack.commands.writeLocalEnvTemplate}`,
    `  - Setup write local env template: ${adProviderOwnerInputPack.commands.setupWriteLocalEnvTemplate}`,
    `  - Sync configured values: ${adProviderOwnerInputPack.commands.syncConfiguredValues}`,
    '',
    'Guardrails:',
    `  - No secret values are stored: ${adProviderOwnerInputPack.controls.noSecretValuesStored}.`,
    `  - Revenue remains gated: ${adProviderOwnerInputPack.controls.noRevenueEnablement}.`,
    `  - Product gates are still required: ${adProviderOwnerInputPack.controls.productGatesStillRequired}.`,
    ...(localTemplateWriteResult
      ? [
          '',
          'Local template writer:',
          `  - Status: ${localTemplateWriteResult.status}`,
          `  - File: ${localTemplateWriteResult.localEnvFile}`,
          `  - Added keys: ${localTemplateWriteResult.addedKeys.join(', ') || 'none'}`,
          `  - Preserved existing values: ${localTemplateWriteResult.preservedExistingValues}.`,
          `  - No secret values written: ${localTemplateWriteResult.noSecretValuesWritten}.`,
          `  - No GitHub mutation: ${localTemplateWriteResult.noGithubMutation}.`,
        ]
      : []),
    '',
  ]

  process.stdout.write(output.join('\n'))
} else {
  console.log(`Wrote ${path.relative(root, outputJsonPath)}`)
  console.log(`Wrote ${path.relative(root, outputTsPath)}`)
  console.log(`Wrote ${path.relative(root, publicManifestPath)}`)
  console.log(`Wrote ${path.relative(root, publicHtmlPath)}`)
  console.log(`Wrote ${path.relative(root, appAdsPath)}`)
  console.log(`Wrote ${path.relative(root, reportPath)}`)
}
